version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
    volumes:
      - ./next
      - ./src:/app/src
      - ./public:/app/public
