export const screenQuestion = {
  CustomQuestion: {
    question: '',
    idealAnswer: 'Yes',
    mustHaveQualification: false,
    responseType: 'yes/no',
    requestContent: false,
    label: 'customQuestion',
  },
  languages: {
    question: 'What is your level of proficiency in __________ ?',
    idealAnswer: 'Conversational',
    mustHaveQualification: false,
    responseType: 'text',
    requestContent: false,
    label: 'languages',
  },
  UrgentHiring: {
    question:
      'We need to fill this position urgently. Can you start immediately?',
    idealAnswer: 'Yes',
    mustHaveQualification: false,
    responseType: 'yes/no',
    requestContent: false,
    label: 'urgent',
  },
  locations: {
    question: 'Are you comfortable commuting to this job’s location?',
    idealAnswer: 'Yes',
    mustHaveQualification: false,
    responseType: 'yes/no',
    requestContent: false,
    label: 'locations',
  },
  VisaStatus: {
    question:
      'Will you now, or in the future, require sponsorship for employment visa status? (e.g. H-1B visa status)?',
    idealAnswer: 'Yes',
    mustHaveQualification: false,
    responseType: 'yes/no',
    requestContent: false,
    label: 'visastatus',
  },
  certification: {
    question:
      'Do you have the following license or certification: __________ ?',
    idealAnswer: 'Yes',
    mustHaveQualification: false,
    responseType: 'yes/no',
    requestContent: false,
    label: 'certificate',
  },
  license: {
    question: 'Do you have a valid driver’s license?',
    idealAnswer: 'Yes',
    mustHaveQualification: false,
    responseType: 'yes/no',
    requestContent: false,
    label: 'driverLicense',
  },
  BackgroundCheck: {
    question:
      'Are you willing to undergo a background check, in accordance with local law/regulations?',
    idealAnswer: 'Yes',
    mustHaveQualification: false,
    responseType: 'yes/no',
    requestContent: false,
    label: 'backgroundCheck',
  },
  DrugTest: {
    question:
      'Are you willing to take a drug test, in accordance with local law/regulations?',
    idealAnswer: 'Yes',
    mustHaveQualification: false,
    responseType: 'yes/no',
    requestContent: false,
    label: 'drugtest',
  },
  WorkAuth: {
    question: 'Are you legally authorized to work in the United States?',
    idealAnswer: 'Yes',
    mustHaveQualification: false,
    responseType: 'yes/no',
    requestContent: false,
    label: 'workautho',
  },
  WorkExpe: {
    question: 'How many years of ________ experience do you currently have?',
    idealAnswer: '1',
    mustHaveQualification: false,
    responseType: 'numeric',
    requestContent: false,
    label: 'workExpre',
  },
  IndustryExcp: {
    question: 'How many years of ________ experience do you currently have?',
    idealAnswer: '1',
    mustHaveQualification: false,
    responseType: 'numeric',
    requestContent: false,
    label: 'industryexcep',
  },
  ExprienceTool: {
    question:
      'How many years of work experience do you have using __________ ?',
    idealAnswer: '1',
    mustHaveQualification: false,
    responseType: 'numeric',
    requestContent: false,
    label: 'exprienecetool',
  },
  GPA: {
    question: 'What is your university grade point average (4.0 GPA Scale)?',
    idealAnswer: '1.00',
    mustHaveQualification: false,
    responseType: 'numeric',
    requestContent: false,
    label: 'gpa',
  },
  education: {
    question:
      'Have you completed the following level of education: __________ ?',
    idealAnswer: 'Yes',
    mustHaveQualification: false,
    responseType: 'yes/no',
    requestContent: false,
    label: 'educ',
  },
};
