import React from 'react';
import PropTypes from 'prop-types';

import {
  IconClose,
  IconEdit,
  IconTrash,
  IconLeftArrow,
  IconPlus,
  IconUpArrow,
  IconPlay,
  IconLogoSquare,
  IconInterview,
  IconBookmarked,
  IconSend,
  IconClock,
  IconJobApplication,
  IconPitch,
  IconProfile,
  IconCalendar,
  IconDrag,
  IconMove,
  IconRightArrow,
  IconThreeDots,
  IconEye,
  IconQuestionMark,
  IconPhone,
  IconMail,
  IconDownArrow,
  IconShare,
  IconPhoto,
  IconUpload,
  IconLove,
  IconAnalytics,
  IconPlusRounded,
  IconLamp,
  IconBucket,
  IconInstagram,
  IconTiktok,
  IconPodcast,
  IconBook,
  IconLink,
  IconTwitter,
  IconWidget,
  IconCheckStroke,
  IconVideoPlay,
  IconLocation,
  IconWarn,
  IconUnEye,
  IconMenu,
  IconPitchOutline,
  IconPitchSolid,
  IconHomeOutline,
  IconHomeSolid,
  IconLibraryOutline,
  IconLibrarySolid,
  IconAplicationOutline,
  IconAplicationSolid,
  IconList,
  IconCard,
  IconLock,
  IconLibraryOutline2,
  IconVideoPlayOutline,
  IconStar,
  IconLogout,
  IconHelpCircle,
  IconWarning,
} from '@assets/svgs';

import { Container } from './styles';
import Loader from '../Loader';

export const iconNames = {
  close: <IconClose />,
  edit: <IconEdit />,
  trash: <IconTrash />,
  leftArrow: <IconLeftArrow />,
  upArrow: <IconUpArrow />,
  downArrow: <IconDownArrow />,
  rightArrow: <IconRightArrow />,
  plus: <IconPlus />,
  play: <IconPlay />,

  logoSquare: <IconLogoSquare />,
  interview: <IconInterview />,
  bookmarked: <IconBookmarked />,
  send: <IconSend />,
  lamp: <IconLamp />,
  clock: <IconClock />,
  jobApplication: <IconJobApplication />,
  pitch: <IconPitch />,
  profile: <IconProfile />,
  calendar: <IconCalendar />,
  drag: <IconDrag />,

  move: <IconMove />,
  threeDots: <IconThreeDots />,
  eye: <IconEye />,
  unEye: <IconUnEye />,
  questionMark: <IconQuestionMark />,
  helpCircle: <IconHelpCircle />,
  phone: <IconPhone />,
  mail: <IconMail />,
  share: <IconShare />,
  photo: <IconPhoto />,
  upload: <IconUpload />,
  love: <IconLove />,
  analytics: <IconAnalytics />,
  plusRounded: <IconPlusRounded />,
  bucket: <IconBucket />,
  instagram: <IconInstagram />,
  tiktok: <IconTiktok />,
  podcasts: <IconPodcast />,
  books: <IconBook />,
  link: <IconLink />,
  twitter: <IconTwitter />,
  widget: <IconWidget />,
  checkStroke: <IconCheckStroke />,
  videoPlay: <IconVideoPlay />,
  videoPlayOutline: <IconVideoPlayOutline />,
  location: <IconLocation />,
  warn: <IconWarn />,
  menu: <IconMenu />,
  pitchOutline: <IconPitchOutline />,
  pitchSolid: <IconPitchSolid />,
  homeOutline: <IconHomeOutline />,
  homeSolid: <IconHomeSolid />,
  libraryOutline2: <IconLibraryOutline2 />,
  libraryOutline: <IconLibraryOutline />,
  librarySolid: <IconLibrarySolid />,
  aplicationOutline: <IconAplicationOutline />,
  aplicationSolid: <IconAplicationSolid />,
  list: <IconList />,
  card: <IconCard />,
  lock: <IconLock />,
  star: <IconStar />,
  logout: <IconLogout />,
  warning: <IconWarning />,
};

const IconSVG = ({ name, size, color, loading }) => {
  return (
    <Container color={color} size={size} className="icon-svg__wrapper">
      {loading ? <Loader size="small" /> : iconNames[name]}
    </Container>
  );
};

IconSVG.propTypes = {
  name: PropTypes.string.isRequired,
  size: PropTypes.number,
  color: PropTypes.string,
  loading: PropTypes.bool,
};

IconSVG.defaultProps = {
  size: 24,
  color: 'currentColor',
  loading: false,
};

export default IconSVG;
